{% set name = "substrait" %}
{% set version = "0.14.1" %}

package:
  name: python-{{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/substrait-{{ version }}.tar.gz
  sha256: cb95859d455a5bcd04fbaae212cd7f900a91be5cc617fd1b39211612e1feacdd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - protobuf >=3.20
    - python >=3.8

test:
  imports:
    - substrait
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/substrait/
  summary: A python package for Substrait.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gforsyth
