{% set name = "substrait" %}
{% set version = "0.26.0" %}

package:
  name: python-{{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/substrait-{{ version }}.tar.gz
  sha256: d96070a1e5ba52ced9fb7e4f35a1b2968160dbe54b24e6dca9db035252aa059d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - protobuf >=3.20
    - python >={{ python_min }}

test:
  imports:
    - substrait
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/substrait/
  summary: A python package for Substrait.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gforsyth
