{% set name = "substrait" %}
{% set version = "0.16.0" %}

package:
  name: python-{{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/substrait-{{ version }}.tar.gz
  sha256: 0cb7cef58be262c1f9d21de1366b3d5d4047f3578099ec3dec9d5de1b61864cd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - protobuf >=3.20
    - python >=3.8

test:
  imports:
    - substrait
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/substrait/
  summary: A python package for Substrait.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gforsyth
