{% set name = "substrait" %}
{% set version = "0.24.1" %}

package:
  name: python-{{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/substrait-{{ version }}.tar.gz
  sha256: e25e131c0709ae64d43d020f49f13e7ab02e9de72c5aafbd3304bc1d71bf7af1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - protobuf >=3.20
    - python >={{ python_min }}

test:
  imports:
    - substrait
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/substrait/
  summary: A python package for Substrait.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gforsyth
