{% set name = "substrait" %}
{% set version = "0.31.0" %}

package:
  name: python-{{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/substrait-{{ version }}.tar.gz
  sha256: fe594cbd5640e77dff5475901cdbdf211b8d76ce13ea86eaeb7d45d47b6a795a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=61
    - setuptools_scm >=6.2
  run:
    - protobuf <7,>=5
    - python >={{ python_min }}
    - python-substrait-extensions ==0.99.0
    - python-substrait-protobuf ==0.99.0
    # - sqloxide 
    # - pyyaml 
    # - python-substrait-antlr ==0.99.0
    # - deepdiff 

test:
  imports:
    - substrait
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/substrait/
  summary: A python package for Substrait.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - yongchul
    - westonpace
    - vbarua
    - jacques-n
    - epsilonprime
    - benbellick
    - nielspardon
    - gforsyth
