{% set name = "substrait" %}
{% set version = "0.7.0" %}

package:
  name: python-{{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/substrait-{{ version }}.tar.gz
  sha256: 3ce2f99517b80dc7b1dc9d38462695ae91a4d54da6c43b9cc48d506b5905adde

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - protobuf >=3.20
    - python >=3.8

test:
  imports:
    - substrait
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/substrait/
  summary: A python package for Substrait.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gforsyth
