{% set name = "substrait" %}
{% set version = "0.12.0" %}

package:
  name: python-{{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/substrait-{{ version }}.tar.gz
  sha256: 84d042dd8a8d0fbf8be4a6c4f466dd5cb8ca39c53d85ef95491ba7a6e8638e41

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - protobuf >=3.20
    - python >=3.8

test:
  imports:
    - substrait
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/substrait/
  summary: A python package for Substrait.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gforsyth
