{% set name = "substrait" %}
{% set version = "0.29.0" %}

package:
  name: python-{{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/substrait-{{ version }}.tar.gz
  sha256: 66a352f8b12aa97a732dd686a36fa4e5faa121cff2eae6d3cb2ceab94b544e69

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=61
    - setuptools_scm >=6.2
  run:
    - protobuf >=5,<7
    - python >={{ python_min }}
    - python-substrait-extensions ==0.85.0
    - python-substrait-protobuf ==0.85.0

test:
  imports:
    - substrait
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/substrait/
  summary: A python package for Substrait.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jacques-n
    - epsilonprime
    - benbellick
    - nielspardon
    - gforsyth
